//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Youtube_Music_Converter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str_ko {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str_ko() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Youtube_Music_Converter.Str.ko", typeof(Str_ko).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 작업 종료..
        /// </summary>
        internal static string str_end {
            get {
                return ResourceManager.GetString("str_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. 빈 텍스트 파일을 큐로 사용하기 위해 만드세요..
        /// </summary>
        internal static string str_help_1 {
            get {
                return ResourceManager.GetString("str_help_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. 해당 파일 내에 VideoLibraray가 지원하는 형식의 주소 (예: Youtube)를 개행을 통해 구분하여 작성 합니다..
        /// </summary>
        internal static string str_help_2 {
            get {
                return ResourceManager.GetString("str_help_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. 해당 txt 파일을 실행 파일에 드래그앤드롭 하거나 아래 명령어 예시를 통하여 실행합니다..
        /// </summary>
        internal static string str_help_3 {
            get {
                return ResourceManager.GetString("str_help_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ 실행_파일 사용자_큐_파일.txt.
        /// </summary>
        internal static string str_help_4 {
            get {
                return ResourceManager.GetString("str_help_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 만약 더 많은 정보나 도움이 필요하다면, 제작자의 Github를 방문 해 주세요..
        /// </summary>
        internal static string str_help_5 {
            get {
                return ResourceManager.GetString("str_help_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  아무 키를 눌러 종료.
        /// </summary>
        internal static string str_help_6 {
            get {
                return ResourceManager.GetString("str_help_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube 음악 변환기.
        /// </summary>
        internal static string str_intro {
            get {
                return ResourceManager.GetString("str_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 매개변수 혹은 파일이 존재 하지 않습니다. 만약 도움말이 필요하다면 아무키를 눌러주세요. 그렇지 않다면 Ctrl + C를 눌러 종료..
        /// </summary>
        internal static string str_no_args {
            get {
                return ResourceManager.GetString("str_no_args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 큐의 URL 목록.
        /// </summary>
        internal static string str_show_queue {
            get {
                return ResourceManager.GetString("str_show_queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 작업 시작..
        /// </summary>
        internal static string str_start {
            get {
                return ResourceManager.GetString("str_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 타겟 파일 : .
        /// </summary>
        internal static string str_target {
            get {
                return ResourceManager.GetString("str_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 전체 작업 수 : .
        /// </summary>
        internal static string str_total_task {
            get {
                return ResourceManager.GetString("str_total_task", resourceCulture);
            }
        }
    }
}
