//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Youtube_Music_Converter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str_ko {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str_ko() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Youtube_Music_Converter.Str.ko", typeof(Str_ko).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 다운로드 실패 : .
        /// </summary>
        internal static string str_download_fail {
            get {
                return ResourceManager.GetString("str_download_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 다운로드중 : .
        /// </summary>
        internal static string str_downloading {
            get {
                return ResourceManager.GetString("str_downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 작업 종료..
        /// </summary>
        internal static string str_end {
            get {
                return ResourceManager.GetString("str_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. 큐를 위한 빈 텍스트 파일을 만드세요..
        /// </summary>
        internal static string str_help_1 {
            get {
                return ResourceManager.GetString("str_help_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. 해당 파일 내에 VideoLibraray가 지원하는 형식의 주소 (예: Youtube)를 개행을 통해 구분하여 작성 합니다..
        /// </summary>
        internal static string str_help_2 {
            get {
                return ResourceManager.GetString("str_help_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. 해당 txt 파일을 실행 파일에 드래그앤드롭 하거나 아래 명령어 예시를 통하여 실행합니다..
        /// </summary>
        internal static string str_help_3 {
            get {
                return ResourceManager.GetString("str_help_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ dotnet Youtube_Music_Converter.dll 사용자_큐.txt.
        /// </summary>
        internal static string str_help_4_linux {
            get {
                return ResourceManager.GetString("str_help_4_linux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube_Music_Converter.exe 사용자_큐.txt.
        /// </summary>
        internal static string str_help_4_windows {
            get {
                return ResourceManager.GetString("str_help_4_windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 만약 더 많은 정보나 도움이 필요하시다면, 아래 Github를 방문 해주십시오..
        /// </summary>
        internal static string str_help_5 {
            get {
                return ResourceManager.GetString("str_help_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube 음악 변환기.
        /// </summary>
        internal static string str_intro {
            get {
                return ResourceManager.GetString("str_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 매개변수 혹은 파일이 없거나 잘못 되었습니다..
        /// </summary>
        internal static string str_no_args {
            get {
                return ResourceManager.GetString("str_no_args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  만약 도움이 필요하시다면 --help 옵션을 사용 해 주십시오..
        /// </summary>
        internal static string str_no_args_with {
            get {
                return ResourceManager.GetString("str_no_args_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 올바른 Youtube URL이 아님 : .
        /// </summary>
        internal static string str_not_support_type {
            get {
                return ResourceManager.GetString("str_not_support_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아무 키를 눌러 계속합니다..
        /// </summary>
        internal static string str_press_key_continue {
            get {
                return ResourceManager.GetString("str_press_key_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 엔터 키를 눌러 종료합니다..
        /// </summary>
        internal static string str_press_key_exit {
            get {
                return ResourceManager.GetString("str_press_key_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 큐의 URL 목록.
        /// </summary>
        internal static string str_show_queue {
            get {
                return ResourceManager.GetString("str_show_queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 작업 시작..
        /// </summary>
        internal static string str_start {
            get {
                return ResourceManager.GetString("str_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 타겟 파일 : .
        /// </summary>
        internal static string str_target {
            get {
                return ResourceManager.GetString("str_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 전체 작업 수 : .
        /// </summary>
        internal static string str_total_task {
            get {
                return ResourceManager.GetString("str_total_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 존재하지 않는 영상 : .
        /// </summary>
        internal static string str_unavailable_stream {
            get {
                return ResourceManager.GetString("str_unavailable_stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 알 수 없는 오류입니다. 같은 디렉토리 내에 있는 로그파일과 함께 이 문제를 제보 해 주십시오..
        /// </summary>
        internal static string str_unknown {
            get {
                return ResourceManager.GetString("str_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 알 수 없는 타입의 파일 입니다. 본 앱은 텍스트 파일 형식 (.txt)만 지원 합니다..
        /// </summary>
        internal static string str_unknown_type {
            get {
                return ResourceManager.GetString("str_unknown_type", resourceCulture);
            }
        }
    }
}
