//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Youtube_Music_Converter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Youtube_Music_Converter.Str", typeof(Str).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Fail : .
        /// </summary>
        internal static string str_download_fail {
            get {
                return ResourceManager.GetString("str_download_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading : .
        /// </summary>
        internal static string str_downloading {
            get {
                return ResourceManager.GetString("str_downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task End..
        /// </summary>
        internal static string str_end {
            get {
                return ResourceManager.GetString("str_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Make empty text file to use queue.
        /// </summary>
        internal static string str_help_1 {
            get {
                return ResourceManager.GetString("str_help_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. In the file, write the address in the format supported by VideoLibraray (eg Youtube) separated by a newline..
        /// </summary>
        internal static string str_help_2 {
            get {
                return ResourceManager.GetString("str_help_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Drag and drop the txt file to the executable file or execute it through the command example below..
        /// </summary>
        internal static string str_help_3 {
            get {
                return ResourceManager.GetString("str_help_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ dotnet Youtube_Music_Converter.dll YOUR_QUEUE.txt.
        /// </summary>
        internal static string str_help_4_linux {
            get {
                return ResourceManager.GetString("str_help_4_linux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube_Music_Converter.exe YOUR_QUEUE.txt.
        /// </summary>
        internal static string str_help_4_windows {
            get {
                return ResourceManager.GetString("str_help_4_windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to read more information or help, please visit My Github..
        /// </summary>
        internal static string str_help_5 {
            get {
                return ResourceManager.GetString("str_help_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube Music Converter.
        /// </summary>
        internal static string str_intro {
            get {
                return ResourceManager.GetString("str_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter or file doesn&apos;t exist or wrong..
        /// </summary>
        internal static string str_no_args {
            get {
                return ResourceManager.GetString("str_no_args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  If you want to get help, use --help option..
        /// </summary>
        internal static string str_no_args_with {
            get {
                return ResourceManager.GetString("str_no_args_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid Youtube URL : .
        /// </summary>
        internal static string str_not_support_type {
            get {
                return ResourceManager.GetString("str_not_support_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue..
        /// </summary>
        internal static string str_press_key_continue {
            get {
                return ResourceManager.GetString("str_press_key_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press enter key to exit..
        /// </summary>
        internal static string str_press_key_exit {
            get {
                return ResourceManager.GetString("str_press_key_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL List in Queue.
        /// </summary>
        internal static string str_show_queue {
            get {
                return ResourceManager.GetString("str_show_queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Start..
        /// </summary>
        internal static string str_start {
            get {
                return ResourceManager.GetString("str_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target File : .
        /// </summary>
        internal static string str_target {
            get {
                return ResourceManager.GetString("str_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Total Task : .
        /// </summary>
        internal static string str_total_task {
            get {
                return ResourceManager.GetString("str_total_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknows Error. Please report this issue with log file (in same directory)..
        /// </summary>
        internal static string str_unknown {
            get {
                return ResourceManager.GetString("str_unknown", resourceCulture);
            }
        }
    }
}
