//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Youtube_Music_Converter_GUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Youtube_Music_Converter_GUI.Str", typeof(Str).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string btn_Add {
            get {
                return ResourceManager.GetString("btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string btn_AddOpen {
            get {
                return ResourceManager.GetString("btn_AddOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btn_Clear {
            get {
                return ResourceManager.GetString("btn_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string btn_Close {
            get {
                return ResourceManager.GetString("btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        internal static string btn_Convert {
            get {
                return ResourceManager.GetString("btn_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string btn_Exit {
            get {
                return ResourceManager.GetString("btn_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string btn_Open {
            get {
                return ResourceManager.GetString("btn_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        internal static string btn_OpenFolder {
            get {
                return ResourceManager.GetString("btn_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string btn_Paste {
            get {
                return ResourceManager.GetString("btn_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string btn_Remove {
            get {
                return ResourceManager.GetString("btn_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;&amp; Convert.
        /// </summary>
        internal static string btn_SaveConvert {
            get {
                return ResourceManager.GetString("btn_SaveConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnRemove.
        /// </summary>
        internal static string btn_UnRemove {
            get {
                return ResourceManager.GetString("btn_UnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string btn_Update {
            get {
                return ResourceManager.GetString("btn_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube Music Converter.
        /// </summary>
        internal static string str_AppName {
            get {
                return ResourceManager.GetString("str_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully changed select language!.
        /// </summary>
        internal static string str_ChangedLanguage {
            get {
                return ResourceManager.GetString("str_ChangedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting has been saved..
        /// </summary>
        internal static string str_ChangedLanguage_Next {
            get {
                return ResourceManager.GetString("str_ChangedLanguage_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check update at startup.
        /// </summary>
        internal static string str_CheckUpdate {
            get {
                return ResourceManager.GetString("str_CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to clear the list?.
        /// </summary>
        internal static string str_Clear {
            get {
                return ResourceManager.GetString("str_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting is in progress. Do you want to exit anyway?.
        /// </summary>
        internal static string str_Converting_exit {
            get {
                return ResourceManager.GetString("str_Converting_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string str_Error {
            get {
                return ResourceManager.GetString("str_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to exit Youtube Music Converter?.
        /// </summary>
        internal static string str_Exit_Sure {
            get {
                return ResourceManager.GetString("str_Exit_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application will be exit..
        /// </summary>
        internal static string str_ExitApp {
            get {
                return ResourceManager.GetString("str_ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t detacted Youtube_Music_Converter.exe . Are you want to set that path manually?.
        /// </summary>
        internal static string str_FindApp {
            get {
                return ResourceManager.GetString("str_FindApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task was interrupted. If exist next task, will be re try.
        /// </summary>
        internal static string str_killed {
            get {
                return ResourceManager.GetString("str_killed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find output directory..
        /// </summary>
        internal static string str_no_dir {
            get {
                return ResourceManager.GetString("str_no_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task List is empty.
        /// </summary>
        internal static string str_no_list {
            get {
                return ResourceManager.GetString("str_no_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always open file at startup.
        /// </summary>
        internal static string str_OpenAtStartup {
            get {
                return ResourceManager.GetString("str_OpenAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output :.
        /// </summary>
        internal static string str_Output {
            get {
                return ResourceManager.GetString("str_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to open new list?.
        /// </summary>
        internal static string str_SureOpen {
            get {
                return ResourceManager.GetString("str_SureOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text files (*.txt)|*.txt.
        /// </summary>
        internal static string str_TextFilter {
            get {
                return ResourceManager.GetString("str_TextFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If wrong with task? Click here to end.
        /// </summary>
        internal static string str_wrong_task {
            get {
                return ResourceManager.GetString("str_wrong_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Feedback.
        /// </summary>
        internal static string strip_Feedback {
            get {
                return ResourceManager.GetString("strip_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string strip_File {
            get {
                return ResourceManager.GetString("strip_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string strip_Help {
            get {
                return ResourceManager.GetString("strip_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Github.
        /// </summary>
        internal static string strip_ProjectGit {
            get {
                return ResourceManager.GetString("strip_ProjectGit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        internal static string strip_Tutorial {
            get {
                return ResourceManager.GetString("strip_Tutorial", resourceCulture);
            }
        }
    }
}
